//PROJECT: E-COMMERCE CHECKOUT CALCULATOR
string productName="Wriless Headphones";
double productPrice=79.99;
int quantity=2;
double discountAmount=15.00;
double taxRate=0.18;
int friendsSharingBill=2;
double subtotal=quantity * productPrice;
double discountedAmount= subtotal - discountAmount;
double taxAmount= discountedAmount * taxRate;
double finalTotal =discountedAmount+taxAmount;
double costPerPerson= finalTotal / friendsSharingBill;
Console.WriteLine("=== RECEIPT ===");
Console.WriteLine("Product: " + productName);
Console.WriteLine("Price: $" + productPrice);
Console.WriteLine("Quantity: " + quantity);
Console.WriteLine("-------------------------");
Console.WriteLine("Subtotal: $" + subtotal);
Console.WriteLine("Discount Applied: -$" + discountAmount);
Console.WriteLine("Tax (18%): $" + taxAmount);
Console.WriteLine("-------------------------");
Console.WriteLine("GRAND TOTAL: $" + finalTotal);
Console.WriteLine("Each person pays (" + friendsSharingBill + " people): $" + costPerPerson);
Console.WriteLine("===============");